sudo: required
services:
    - docker
before_install:
    # run the tests that are inside client project
    - docker build -t skvisha/react-test -f ./client/Dockerfile.dev ./client

#primary test running section
script:
  - docker run skvisha/react-test npm test -- --coverage

after_success:
  - docker build -t skvisha/multi-client ./client
  - docker build -t skvisha/multi-nginx ./nginx
  - docker build -t skvisha/multi-server ./server
  - docker build -t skvisha/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PSWD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to docker hub
  - docker push skvisha/multi-client
  - docker push skvisha/multi-nginx
  - docker push skvisha/multi-server
  - docker push skvisha/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1" #taken from aws url for the project
  app: "multi-docker"
  env: "MultiDocker-env"
  #S3 storage where zip with all files shouold be put to
  # find it in aws->S3
  bucket_name: "elasticbeanstalk-eu-central-1-941462630206" 
  bucket_path: "docker-multi" #app name
  on:
    branch: master # deploy from master branch,when new code appears there
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  
